In [43]:
import pandas as pd
import numpy as np

In [44]:
random_matrix = np.random.randint(20, size=(4,4))

In [45]:
random_matrix

array([[ 0, 13,  4,  3],
       [ 3, 13, 10,  2],
       [11, 19, 14, 10],
       [12, 17, 17, 19]], dtype=int32)

In [46]:
# numpy array to pandas dataframe
df = pd.DataFrame(random_matrix, columns = ["A Return", "B Return", "C Return", "D Return"])

In [47]:
df

   A Return  B Return  C Return  D Return
0         0        13         4         3
1         3        13        10         2
2        11        19        14        10
3        12        17        17        19

In [48]:
df.iloc[0:2,2] # iloc metodu ile sütunlar üzerinden arama örneği. (satırlar için de yapılabiliyor.)

0     4
1    10
Name: C Return, dtype: int32

In [49]:
df.iloc[0]

A Return     0
B Return    13
C Return     4
D Return     3
Name: 0, dtype: int32

In [50]:
df > 10 # boolen matris döndürüyor.

   A Return  B Return  C Return  D Return
0     False      True     False     False
1     False      True     False     False
2      True      True      True     False
3      True      True      True      True

In [51]:
df[df > 10] # boolen matris verirsem o değerleri döndürüyor.

   A Return  B Return  C Return  D Return
0       NaN        13       NaN       NaN
1       NaN        13       NaN       NaN
2      11.0        19      14.0       NaN
3      12.0        17      17.0      19.0

In [52]:
df["A Return"] > 10

0    False
1    False
2     True
3     True
Name: A Return, dtype: bool

In [53]:
df[df["A Return"] > 10]

   A Return  B Return  C Return  D Return
2        11        19        14        10
3        12        17        17        19

In [54]:
type(df["A Return"])

pandas.core.series.Series